Replace usage of NaiveTime::from_hms with NaiveTime::from_hms_opt
isaacrlee/event-parser pull request #8
Opened 2022-08-21 14:12 UTC by joajfreitas

All usages of from_hms where already returning an Option<T> so by using
from_hms_opt we avoid panics without having to change any function
signature.

2022-08-27 03:00 UTC, isaacrlee requested changes
Thanks for adding this, I can see the advantages of using `from_hms_opt` instead of `from_hms`. Before merging this in, would like to see the compilation error fixed and some tests for the new functionality. Maybe something like:
```
    #[test]
    fn invalid_time_tests() {
        assert_eq!(TimeExpr::recognize("24"), None);
        assert_eq!(TimeExpr::recognize("99:99"), None);
    }
```

2022-08-27 10:46 UTC, joajfreitas commented on date_time_parser/src/time_parse.rs
> +            )?))
I also tested it locally and I couldn't reproduce the compilation error. Can you provide the toolchain you are using? Obviously I can just revert the change back but I would like to be sure that I am not introducing any new problems

2022-08-28 19:12 UTC, isaacrlee approved these changes

2022-08-28 19:16 UTC, isaacrlee commented
Everything looks good to me. I'll merge this in then add a commit updating the version of `date_time_parser` to 0.2.0. It might be a little while before we get the new version up to crates.io but that will happen eventually. Thanks for adding this @joajfreitas!

2022-08-28 19:16 UTC, merged